### ISSUE TITLE
Tree rendering, however, errors out when dragging.

### ISSUE THREAD

**Issue by aclayton** [phphe/vue-draggable-nested-tree#8]
vue-draggable-nested-tree.es.js:805 failed to execute rule 'targetNode is placeholder' TypeError: Cannot read property 'getBoundingClientRect' of null

**Comment by phphe** [comment]
That will not cause bad influence. You can see its color is yellow and type is warning not error. 
It is caught and throw out by console.warn. Dont worry it and it is rare. 
The warn looks like follow:
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 failed to execute rule 'targetNode is placeholder' TypeError: Cannot read property 'getBoundingClientRect' of null
    at getOffset (https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:180:19)
    at https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:2082:22
    at binarySearch (https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:287:11)
    at Object.targetNode (https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:2080:19)
    at https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:1763:33
    at Cache.remember (https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:1735:20)
    at Object.get (https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:1762:24)
    at targetNodeIsPlaceholder (https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:1866:19)
    at Object.rules.(anonymous function) [as targetNode is placeholder] (https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:1944:26)
    at exec (https://unpkg.com/vue-draggable-nested-tree@2.0.1/dist/vue-draggable-nested-tree.js:2161:28)
